* PKGBUILD FOR FLOP DESIGN FONTS

** これはなんですか
   [[http://www.flopdesign.com/freefont/flopdesignfont.html][フロップデザインフォント]] をArch Linuxおよびその派生ディストリビューションにインストールするためのPKGBUILDです。

   Arch Linuxにおいてはフォントのインストールにパッケージ化が推奨されています。

** つかいかた（かんたん）
   AURに登録しました。yaourtをインストールしている場合
   
   : yaourt -S otf-flop-design

   でインストールできます。
   
   その他AURを叩けるパッケージ管理ソフトでも同様にインストールできます。

** つかいかた（めんどう？）
   このリポジトリから落としてインストールする場合
   
   : git clone git@github.com:boronology/otf-flop-design.git
   : cd otf-flop-design
   : makepkg
   : sudo pacman -U *.pkg.tar.xz

   でインストールできます。

** フォントの詳細
   [[http://www.flopdesign.com/index.html][FLOP DESIGN]]様の開発した第二水準漢字までを含むフォントです。

   このパッケージではOpenType FontとTrueType Fontの両方がインストールされます。
   
   サンプルは [[http://www.flopdesign.com/freefont/flopdesignfont.html][公式サイト]] をご覧ください

** フォントのライセンス
   IPAフォントライセンスが関わるため多少複雑になっています。

   詳しくは [[http://www.flopdesign.com/freefont/flopdesignfont.html][公式サイト]] をご覧ください。
   
** バージョン
   2013/07/17 TrueType Fontが追加されたのに対応しました。

   AURに投稿したのでちゃんとメンテしていきます。

** 更新履歴

*** 2013/07/16
    Twitterで話題になってたので作ってみた。

*** 2013/07/17
    本家のファイルの名前変更とTrueType追加に対応した。

*** 2013/07/18
    本家の更新の早さに驚きつつ更新に対応した（md5の書き換えのみ）

*** 2013/07/31
    本家の更新に対応。といっても同じく書き換えのみ。

*** 2013/9/6
    本家のダウンロードURLが変更されていたので修正。

*** 2013/10/15
    知らないうちに本家のパッケージが更新されていたので修正。
    （チェックサムのみ）

*** 2013/11/30
    AURのカテゴリにFontsができていたのでx11カテゴリから移す。

*** 2014/1/10
    本家が更新されていたので修正。
    FLOPDESIGN_FONTからFLOPDESIGN-FONTに変わったのはぱっと見わからなかった。

*** 2014/1/13
    ファイル名も変更されてたので修正。
    OpenTypeがFlopDesignFontでTrueTypeがFLOPDesignFontなのは一体。
